In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn import metrics

In [3]:
#Data Collection and Preprcessing
#loaing data from csv to pd

car_data = pd.read_csv('car data.csv')

In [4]:
car_data.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [5]:
#checking no of rows and column
car_data.shape

(301, 9)

In [6]:
#checking no of missing values
car_data.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [7]:
#checking distribution of catagorical data
print(car_data.Fuel_Type.value_counts())
print(car_data.Seller_Type.value_counts())
print(car_data.Transmission.value_counts())

Fuel_Type
Petrol    239
Diesel     60
CNG         2
Name: count, dtype: int64
Seller_Type
Dealer        195
Individual    106
Name: count, dtype: int64
Transmission
Manual       261
Automatic     40
Name: count, dtype: int64

In [8]:
#encoding catagorical values
car_data.replace({'Fuel_Type': {'Petrol' : 0, 'Diesel' : 1, 'CNG': 2}},inplace= True)
car_data.replace({'Seller_Type': {'Dealer' : 0, 'Individual' : 1}},inplace= True)
car_data.replace({'Transmission': {'Manual' : 0, 'Automatic' : 1}},inplace= True)

C:\Users\zeyaa\AppData\Local\Temp\ipykernel_14956\64875740.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  car_data.replace({'Fuel_Type': {'Petrol' : 0, 'Diesel' : 1, 'CNG': 2}},inplace= True)
C:\Users\zeyaa\AppData\Local\Temp\ipykernel_14956\64875740.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  car_data.replace({'Seller_Type': {'Dealer' : 0, 'Individual' : 1}},inplace= True)
C:\Users\zeyaa\AppData\Local\Temp\ipykernel_14956\64875740.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  car_data.replace({'Transmission': {'Manual' : 0, 'Automatic' : 1}},inplace= True)

In [9]:
car_data.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,0,0,0,0
1,sx4,2013,4.75,9.54,43000,1,0,0,0
2,ciaz,2017,7.25,9.85,6900,0,0,0,0
3,wagon r,2011,2.85,4.15,5200,0,0,0,0
4,swift,2014,4.60,6.87,42450,1,0,0,0

In [10]:
#splitting data int training and test
x = car_data.drop(['Car_Name', 'Selling_Price'],axis = 1)
y = car_data['Selling_Price']

In [11]:
print(x)

     Year  Present_Price  Kms_Driven  Fuel_Type  Seller_Type  Transmission  \
0    2014           5.59       27000          0            0             0
1    2013           9.54       43000          1            0             0
2    2017           9.85        6900          0            0             0
3    2011           4.15        5200          0            0             0
4    2014           6.87       42450          1            0             0
..    ...            ...         ...        ...          ...           ...
296  2016          11.60       33988          1            0             0
297  2015           5.90       60000          0            0             0
298  2009          11.00       87934          0            0             0
299  2017          12.50        9000          1            0             0
300  2016           5.90        5464          0            0             0

     Owner
0        0
1        0
2        0
3        0
4        0
..     ...
296      0
297      0
298      0
299      0
300      0

[301 rows x 7 columns]

In [12]:
print(y)

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

In [13]:
x_train, x_test, y_train,y_test = train_test_split(x, y, test_size =  0.1, random_state= 2)

In [14]:
#loading linear regresion model
lin_reg_model = LinearRegression()

In [15]:
lin_reg_model.fit(x_train, y_train)

LinearRegression()

In [16]:
training_data_prediction = lin_reg_model.predict(x_train)

In [17]:
error_score = metrics.r2_score(y_train, training_data_prediction)
print(f" r square error is : {error_score}")

 r square error is : 0.87994516604937

In [18]:
test_data_prediction = lin_reg_model.predict(x_test)

In [19]:
error_score = metrics.r2_score(y_test, test_data_prediction)
print(f" r square error is : {error_score}")

 r square error is : 0.836576671502693

In [20]:
#laso regression

las_reg_model = Lasso()

In [21]:
las_reg_model.fit(x_train, y_train)

Lasso()

In [22]:
training_data_prediction = las_reg_model.predict(x_train)

In [23]:
error_score = metrics.r2_score(y_train, training_data_prediction)
print(f" r square score is : {error_score}")

 r square score is : 0.8427856123435794

In [24]:
test_data_prediction = las_reg_model.predict(x_test)

In [25]:
error_score = metrics.r2_score(y_test, test_data_prediction)
print(f" r square score is : {error_score}")

 r square score is : 0.8709167941173195